---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: docker.io/dhubau/payment-service:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_RABBITMQ_HOST
              value: rabbit-production-rabbitmq.data.svc.cluster.local
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: rabbitmq-password
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_ENABLED
              value: 'true'
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
              value: 'proxy://wavefront-proxy:2878'
            - name: WAVEFRONT_APPLICATION_NAME
              value: tanzu-demo-prod
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            requests:
              memory: 768Mi
              cpu: 500m
            limits:
              memory: 768Mi
          ports:
            - containerPort: 8080
