---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      containers:
        - name: wavefront-proxy
          image: wavefronthq/proxy:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WAVEFRONT_URL
              value: 'https://vmware.wavefront.com'
            - name: WAVEFRONT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wavefront
                  key: token
          ports:
            - name: tcp-metrics
              containerPort: 2878
              protocol: TCP
